import { TestEndpoint, TestCategory } from './types.ts';

export const CATEGORIES: TestCategory[] = [
    'Google',
    'Meta',
    'Amazon',
    'Microsoft',
    'Social',
    'Mobile',
    'Programmatic',
    'Native',
    'eCommerce',
    'Audio',
    'Analytics',
    'Other'
];

export const TEST_ENDPOINTS: TestEndpoint[] = [
  { url: 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js', category: 'Google', weight: 1 },
  { url: 'https://securepubads.g.doubleclick.net/tag/js/gpt.js', category: 'Google', weight: 1 },
  { url: 'https://www.googletagservices.com/tag/js/gpt.js', category: 'Google', weight: 1 },
  { url: 'https://googleads.g.doubleclick.net/pagead/ads', category: 'Google', weight: 1 },
  { url: 'https://adservice.google.com/adsid/integrator.js', category: 'Google', weight: 1 },
  { url: 'https://www.youtube.com/pagead/lvz', category: 'Google', weight: 3 },
  { url: 'https://www.google.com/pagead/lvz', category: 'Google', weight: 3 },
  { url: 'https://www.youtube.com/get_midroll_info', category: 'Google', weight: 3 },
  { url: 'https://www.youtube.com/ptracking', category: 'Google', weight: 3 },
  { url: 'https://www.youtube.com/api/stats/ads', category: 'Google', weight: 3 },
  { url: 'https://www.youtube.com/youtubei/v1/player/ad_break', category: 'Google', weight: 3 },
  { url: 'https://static.doubleclick.net/instream/ad_status.js', category: 'Google', weight: 1 },
  { url: 'https://imasdk.googleapis.com/js/sdkloader/ima3.js', category: 'Google', weight: 1 },
  { url: 'https://connect.facebook.net/en_US/fbevents.js', category: 'Meta', weight: 1 },
  { url: 'https://www.facebook.com/tr', category: 'Meta', weight: 1 },
  { url: 'https://connect.facebook.net/signals/config', category: 'Meta', weight: 1 },
  { url: 'https://www.instagram.com/ads/', category: 'Meta', weight: 1 },
  { url: 'https://aax.amazon-adsystem.com/e/dtb/bid', category: 'Amazon', weight: 1 },
  { url: 'https://s.amazon-adsystem.com/iu3', category: 'Amazon', weight: 1 },
  { url: 'https://c.amazon-adsystem.com/aax2/apstag.js', category: 'Amazon', weight: 1 },
  { url: 'https://bat.bing.com/bat.js', category: 'Microsoft', weight: 1 },
  { url: 'https://ads.linkedin.com/collect/', category: 'Microsoft', weight: 1 },
  { url: 'https://api.searchads.apple.com/v1', category: 'Social', weight: 1 },
  { url: 'https://analytics.tiktok.com/i18n/pixel/events.js', category: 'Social', weight: 1 },
  { url: 'https://analytics.tiktok.com/i18n/pixel/config.js', category: 'Social', weight: 1 },
  { url: 'https://static.ads-twitter.com/uwt.js', category: 'Social', weight: 1 },
  { url: 'https://analytics.twitter.com/i/adsct', category: 'Social', weight: 1 },
  { url: 'https://s.pinimg.com/ct/core.js', category: 'Social', weight: 1 },
  { url: 'https://ct.pinterest.com/v3/', category: 'Social', weight: 1 },
  { url: 'https://api.ad.unity3d.com/v1/games', category: 'Mobile', weight: 1 },
  { url: 'https://d.applovin.com/v1/ad', category: 'Mobile', weight: 1 },
  { url: 'https://init.supersonicads.com/sdk/v1', category: 'Mobile', weight: 1 },
  { url: 'https://sdk-api-v1.inmobicdn.net/sdk/android', category: 'Mobile', weight: 1 },
  { url: 'https://api.vungle.com/api/v5', category: 'Mobile', weight: 1 },
  { url: 'https://adc3-launch.adcolony.com/v4/launch', category: 'Mobile', weight: 1 },
  { url: 'https://ads.mopub.com/m/ad', category: 'Mobile', weight: 1 },
  { url: 'https://graph.chartboost.com/api/v3', category: 'Mobile', weight: 1 },
  { url: 'https://ib.adnxs.com/ut/v3/prebid', category: 'Programmatic', weight: 1 },
  { url: 'https://secure.adnxs.com/ptv', category: 'Programmatic', weight: 1 },
  { url: 'https://us-u.openx.net/w/1.0/pd', category: 'Programmatic', weight: 1 },
  { url: 'https://fastlane.rubiconproject.com/a/api/fastlane.json', category: 'Programmatic', weight: 1 },
  { url: 'https://ads.rubiconproject.com/prebid/load-cookie.html', category: 'Programmatic', weight: 1 },
  { url: 'https://ads.pubmatic.com/AdServer/js/pwt/pwt.js', category: 'Programmatic', weight: 1 },
  { url: 'https://image8.pubmatic.com/AdServer/SPug', category: 'Programmatic', weight: 1 },
  { url: 'https://js-sec.indexww.com/ht/p/index-v1.js', category: 'Programmatic', weight: 1 },
  { url: 'https://ib.3lift.com/ttj', category: 'Programmatic', weight: 1 },
  { url: 'https://cdn.taboola.com/libtrc/loader.js', category: 'Native', weight: 1 },
  { url: 'https://trc.taboola.com/sg/loader.js', category: 'Native', weight: 1 },
  { url: 'https://widgets.outbrain.com/outbrain.js', category: 'Native', weight: 1 },
  { url: 'https://native.sharethrough.com/assets/sfp.js', category: 'Native', weight: 1 },
  { url: 'https://s.adroll.com/j/roundtrip.js', category: 'eCommerce', weight: 1 },
  { url: 'https://d.adroll.com/ipixel', category: 'eCommerce', weight: 1 },
  { url: 'https://static.criteo.net/js/ld/ld.js', category: 'eCommerce', weight: 1 },
  { url: 'https://gum.criteo.com/syncframe', category: 'eCommerce', weight: 1 },
  { url: 'https://ad.propellerads.com/js/', category: 'eCommerce', weight: 1 },
  { url: 'https://cdn.propellerads.com/tags.js', category: 'eCommerce', weight: 1 },
  { url: 'https://a.adtng.com/', category: 'eCommerce', weight: 1 },
  { url: 'https://syndication.adsterra.com/', category: 'eCommerce', weight: 1 },
  { url: 'https://wl.spotify.com', category: 'Audio', weight: 3 },
  { url: 'https://ads.spotify.com/api/v1/ads', category: 'Audio', weight: 3 },
  { url: 'https://spclient.wg.spotify.com/ads/v1/ads', category: 'Audio', weight: 3 },
  { url: 'https://www.google-analytics.com/analytics.js', category: 'Analytics', weight: 1 },
  { url: 'https://www.googletagmanager.com/gtag/js', category: 'Analytics', weight: 1 },
  { url: 'https://www.google-analytics.com/collect', category: 'Analytics', weight: 1 },
  { url: 'https://static.hotjar.com/c/hotjar-', category: 'Analytics', weight: 1 },
  { url: 'https://cdn.segment.com/analytics.js/v1', category: 'Analytics', weight: 1 },
  { url: 'https://js.hs-analytics.net/analytics', category: 'Analytics', weight: 1 },
  { url: 'https://www.clarity.ms/tag/', category: 'Analytics', weight: 1 },
  { url: 'https://g2.gumgum.com/javascripts/ggv2.js', category: 'Other', weight: 1 },
  { url: 'https://bs.serving-sys.com/BurstingPipe/adServer.bs', category: 'Other', weight: 1 },
  { url: 'https://tags.expo9.exponential.com/tags/exponential.js', category: 'Other', weight: 1 },
  { url: 'https://ap.lijit.com/www/delivery/fp', category: 'Other', weight: 1 },
  { url: 'https://contextual.media.net/dmedianet.js', category: 'Other', weight: 1 },
  { url: 'https://js.spotx.tv/easi/v1/123.js', category: 'Other', weight: 1 },
  { url: 'https://a.teads.tv/page/123/tag', category: 'Other', weight: 1 },
];